name:                hyperscript
version:             0.1.0.1
github:              "MonadicSystems/hyperscript"
license:             BSD3
author:              "Monadic Systems LLC"
maintainer:          "tech@monadic.systems"
copyright:           "2022 Monadic Systems LLC"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A parser for the _hyperscript programming language
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/MonadicSystems/hyperscript#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- parser-combinators
- text

library:
  source-dirs: src

executables:
  hyperscript-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hyperscript

tests:
  hyperscript-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hyperscript
    - hspec
